spring:
  datasource:
    username: root
    password: n
    url: jdbc:mysql://localhost:3306/shopproduct
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.gdbargain: debug
include-binding-errors: always
include-message: always