spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

#        - id: admin_route
#          uri: http://localhost:8080/renren-fast/captcha.jpg?uuid=631bef5f-de70-4d6c-8a1e-8df3a144043d
#          predicates:
#            - Path=/a/**

#        - id: a_route
#          uri: http://localhost:8080/renren-fast/**
#          predicates:
#            - Path=/api/**

#        - id: product_route
#          uri: http://localhost:10000/product/category/list/tree
#          uri: https://www.qq.com
#          uri: http://localhost:8080/renren-fast/captcha.jpg?uuid=830e5fc9-3e7a-4c05-8f02-f410dbad31af
#          uri: lb://renren-fast

#          predicates:
#            - Path=/api/**
#            - Method=get
#          filter:
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} # 重写路径

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**  # 前端项目默认  /api
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} # 重写路径
#            - RewritePath=/api/?(?<segment>.*), /renren-fast\{segment}
